routes/web.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\BatchController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DefaultController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\CoursePayController;
use App\Http\Controllers\OurTeamController;
use App\Http\Controllers\RealEventController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\AdvocateController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\CashInHandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CreateAdminController;
use App\Http\Controllers\CustomerApproveController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerInvoiceController;
use App\Http\Controllers\CustomerTransactionController;
use App\Http\Controllers\DomainController;
use App\Http\Controllers\DomainHostingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EstimateController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\HostingController;
use App\Http\Controllers\InvestorController;
use App\Http\Controllers\InvestorPayController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\PermissionAssignController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SubModuleController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskUpdateController;
use App\Http\Controllers\TransactionController;
use App\Models\Transaction;
use Illuminate\Support\Facades\Route;


Route::redirect('/', 'dashboard');
Route::match(['get', 'post'], '/register', [AdminAuthController::class, 'register'])->name('register');
Route::match(['get', 'post'], '/login', [AdminAuthController::class, 'login'])->name('login');
Route::match('get', '/logout', [AdminAuthController::class, 'logout'])->name('admin.logout');
Route::match(['get', 'post'], '/my-profile/{id}', [AdminAuthController::class, 'myProfile'])->name('my.profile');
Route::match(['get', 'post'], '/change/password/{id}', [AdminAuthController::class, 'changePassword'])->name('change.password');

Route::group(['middleware' => ['adminAuth']], function () {
    Route::match(['get'], '/dashboard', [DashboardController::class, 'dashboard'])->name('admin.dashboard');

    //customer
    Route::resource('customer', CustomerController::class);
    //Product & Service
    Route::resource('service', ServiceController::class);
    //Traction
    Route::resource('transaction', TransactionController::class);
    //Invoice
    Route::resource('invoice', InvoiceController::class);
    //employee
    Route::resource('employee', EmployeeController::class);
    //task
    Route::resource('task', TaskController::class);
    //taskUpdate
    Route::resource('taskUdate', TaskUpdateController::class);

    //transaction_customer
    Route::post('/createdCustomer', [CustomerTransactionController::class, 'index'])->name('customer.transaction');
    Route::post('/invoiceCustomer', [CustomerInvoiceController::class, 'invoiceCustomer'])->name('customer.invoice');
    //attendance
    Route::get('/attendance',[AttendanceController::class,'Attendance'])->name('attendance');
    Route::post('/create/attendance',[AttendanceController::class,'createAttendance'])->name('create.attendance');
    Route::get('/get/attendance',[AttendanceController::class,'getAttendance'])->name('get.attendance');
    Route::get('/end/attendance/{id}',[AttendanceController::class,'endAttendance'])->name('end.attendance');
    Route::post('/update/attendance/{id}',[AttendanceController::class,'updateAttendance'])->name('update.attendance');
    Route::get('/unblockEmployee',[AttendanceController::class,'unblockEmployee'])->name('unblockEmployee');
    Route::post('/unblockEmployee',[AttendanceController::class,'unblockEmployeePost'])->name('unblockEmployeePost');
    Route::get('/delete/unblock{id}',[AttendanceController::class,'deleteUnblock'])->name('delete.unblock');
    //invoicePdf
    Route::get('/invoicePdf/{id}', [PdfController::class, 'invoicePdf'])->name('invoicePdf');

    //employeePrint
    Route::get('/employeePrint/{id}', [PdfController::class, 'employeePrint'])->name('employeePrint');

    //Task_status
    Route::get('taskStatus/{id}', [TaskController::class, 'taskStatus'])->name('taskStatus');
    //Task_progress_status
    Route::get('taskProgressStatus/{id}', [TaskController::class, 'taskProgressStatus'])->name('taskProgressStatus');
    //maintenanece
    Route::get('maintenance/{id}', [TaskController::class, 'maintenance'])->name('maintenance');
    Route::get('ongoing/{id}', [CustomerController::class, 'ongoing'])->name('ongoing');

    //ajax
    Route::post('/getPrice', [AjaxController::class, 'getPrice']);

    //customerList for dashboard
    Route::get('/customerList', [CustomerController::class, 'customerList'])->name('customerList');
    Route::post('/customerDelete/{id}', [CustomerController::class, 'customerDelete'])->name('customerDelete');
    //customer Approve
    Route::get('/customerApprove', [CustomerApproveController::class, 'customerApprove'])->name('customer.approve');
    
    //receivable Amount for dashboard
    Route::get('/receivableCurrent', [DashboardController::class, 'receivableCurrent'])->name('receivableCurrent');
    //CurrentIncome for dashboard
    Route::get('/currentIncomeList', [DashboardController::class, 'currentIncomeList'])->name('currentIncomeList');
    //totalIncome for dashboard
    Route::get('/totalIncomeList', [DashboardController::class, 'totalIncomeList'])->name('totalIncomeList');
    //activeProjectList for dashboard
    Route::get('/activeProjectList', [DashboardController::class, 'activeProjectList'])->name('activeProjectList');
    //inactiveProjectList for dashboard
    Route::get('/inactiveProjectList', [DashboardController::class, 'inactiveProjectList'])->name('inactiveProjectList');
    //completedProjectList for dashboard
    Route::get('/completedProjectList', [DashboardController::class, 'completedProjectList'])->name('completedProjectList');
    //maintenanceList
    Route::get('/maintenanceList', [DashboardController::class, 'maintenanceList'])->name('maintenanceList');
    // //investor_pay
    Route::match(['get', 'post'], '/investor_pay', [InvestorPayController::class, 'investor_pay'])->name('investor_pay');

    Route::match(['get'], '/payment/list', [InvestorPayController::class, 'paymentList'])->name('payment.list');

    Route::match(['get'], '/investorPay_delete/{id}', [InvestorPayController::class, 'investorPayDelete'])->name('investorPay_delete');
    //maintenance_get
    Route::match(['get', 'post'], '/maintenance_get', [MaintenanceController::class, 'maintenance_get'])->name('maintenance_get');
    //maintenance_list
    Route::match(['get'], '/maintenance_list', [MaintenanceController::class, 'maintenance_list'])->name('maintenance_list');
    Route::post('/mantenaceDelete/{id}',[MaintenanceController::class,'mantenaceDelete'])->name('mantenaceDelete');
    Route::match(['get','post'],'/maintenancePay',[MaintenanceController::class,'maintenancePay'])->name('maintenancePay');
    //maintenanceDue
    Route::match(['get'], '/maintenanceDue', [MaintenanceController::class, 'maintenanceDue'])->name('maintenanceDue');
    //maintenancePaid
    Route::match(['get'], '/maintenancePaid', [MaintenanceController::class, 'maintenancePaid'])->name('maintenancePaid');

    //estimate.create
    Route::match(['get','post'],'/estimate/create',[EstimateController::class,'estimate_create'])->name('estimate.create');
    Route::match(['get'],'/estimate/list',[EstimateController::class,'estimateList'])->name('estimateList');
    Route::match(['post'],'/estimateDestroy/{id}',[EstimateController::class,'estimateDestroy'])->name('estimateDestroy');
    Route::match(['get'],'/estimateView/{id}',[EstimateController::class,'estimateView'])->name('estimateView');
    Route::match(['get'],'/estimatePdf/{id}',[PdfController::class,'estimatePdf'])->name('estimatePdf');

    // //Task
    Route::match(['get'], '/getName', [AjaxController::class, 'getName'])->name('getName');
    Route::match(['get'], '/getMaintenanceAmount', [AjaxController::class, 'getMaintenanceAmount'])->name('getMaintenanceAmount');

    // //investorPay_print
    Route::match(['get'], '/investorPay_print/{id}', [PdfController::class, 'investorPay_print'])->name('investorPay_print');

    // //bookingInvoice
    Route::match(['get'], '/bookingInvoice/{id}', [PdfController::class, 'bookingInvoice'])->name('bookingInvoice');
    //investorPay_View
    Route::match(['get'],'/investorPay_View/{id}',[InvestorPayController::class,'investorPay_View'])->name('investorPay_View');
    //category.index
    Route::match(['get','post'],'/category/list',[CategoryController::class,'category_index'])->name('category.index');
    Route::match(['post'],'/category/delete/{id}',[CategoryController::class,'category_delete'])->name('category_delete');
    Route::match(['get'],'/expense/list',[ExpenseController::class,'expenselist'])->name('expenselist');
    Route::match(['get'],'/expensePost/list',[ExpenseController::class,'expensePost'])->name('expensePost');
    Route::match(['get','post'],'/expense/create',[ExpenseController::class,'expenseCreate'])->name('expenseCreate');
    

resources/views/backend/dashboard/activeProjectList.blade.php
@extends('backend.partials.app')
@section('content')
@push('css')
<style>
    .add-btn {
        width: 60px;
        height: 60px;
        background: #ef5252;
        display: inline-block;
        text-align: center;
        line-height: 60px;
        border-radius: 50%;
        font-size: 30px;
        color: aliceblue;
        cursor: pointer;
    }

    .customer-card {
        display: flex;
        justify-content: space-between;
    }
    .customer-container {
        margin: 0 0 310px 0;
    }

</style>
<link href="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
@endpush
<!-- Hoverable Table rows -->
<div class="container customer-container">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="customer-card mb-3" style="margin-top:-10px;">
                        <div class="area-h3">
                            <h2>Ongoing Project List</h2>
                        </div>

                        {{-- <div class="print">
                            <a href="" class="btn btn-primary pdf">CSV</a>
                            <a href="" class="btn btn-primary pdf">Excel</a>
                             <a class="btn btn-primary pdf" href="">PDF</a>
                             <a class="btn btn-primary pdf btnprn" href="" onclick="print()">Print</a>
                            </div> --}}

                    </div>
                    <table class="table table-hover table-borderd" id="example">
                        <thead>
                            <tr>
                                <th>SI</th>
                                <th>Employee Name</th>
                                <th>Title</th>
                                <th>Assign Date</th>
                                <th>Status</th>
                                <th>Progress Status</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $i = 1 @endphp
                            @foreach($activeProjectList as $value)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $value->employee->name }}</td>
                                <td>{{ $value->customer->name_or_business }}</td>
                                <td>{{ date('d-M-Y', strtotime($value->assign_date)) }}</td>
                                <td>
                                    @if($value->status == 'active')
                                    <a class="btn btn-success" href="{{ route('taskStatus',$value->id) }}">{{ $value->status }}</a>
                                    @elseif($value->status == 'inactive')
                                    <a class="btn btn-danger" href="{{ route('taskStatus',$value->id) }}">{{ $value->status }}</a>
                                    @endif

                                </td>
                                <td>
                                    @if($value->progress_status == 'incomplete')
                                    <a class="btn btn-danger" href="{{ route('taskProgressStatus',$value->id) }}">{{ $value->progress_status }}</a>
                                    @else
                                    <a class="btn btn-success" href="{{ route('taskProgressStatus',$value->id) }}">{{ $value->progress_status }}</a>
                                    @endif

                                </td>
                                <td>{{ Str::limit($value->description,20) }}</td>
                                <td>
                                    <div class="action-buttons">
                                        <a class="btn btn-dark" href="{{ route('task.edit',$value->id) }}"><i class="fas fa-edit"></i></a>

                                        <form action="{{ route('task.destroy',$value->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                        </form>
                                    </div>

                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<!--/ Hoverable Table rows -->

@endsection
@push('js')
<script src="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.js"></script>
<script>
    new DataTable('#example', {
        select: true
    });

</script>
@endpush

resources/views/backend/dashboard/completedProjectList.blade.php
@extends('backend.partials.app')
@section('content')
@push('css')
<style>
    .add-btn {
        width: 60px;
        height: 60px;
        background: #ef5252;
        display: inline-block;
        text-align: center;
        line-height: 60px;
        border-radius: 50%;
        font-size: 30px;
        color: aliceblue;
        cursor: pointer;
    }

    .customer-card {
        display: flex;
        justify-content: space-between;
    }

    .customer-container {
        margin: 0 0 310px 0;
    }

</style>
<link href="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
@endpush
<!-- Hoverable Table rows -->
<div class="container customer-container">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="customer-card mb-3" style="margin-top:-10px;">
                        <div class="area-h3">
                            <h2>Completed Project List</h2>
                        </div>

                        {{-- <div class="print">
                            <a href="" class="btn btn-primary pdf">CSV</a>
                            <a href="" class="btn btn-primary pdf">Excel</a>
                             <a class="btn btn-primary pdf" href="">PDF</a>
                             <a class="btn btn-primary pdf btnprn" href="" onclick="print()">Print</a>
                            </div> --}}

                    </div>
                    <table class="table table-hover table-borderd" id="example">
                        <thead>
                            <tr>
                                <th>SI</th>
                                <th>Employee Name</th>
                                <th>Title</th>
                                <th>Assign Date</th>
                                <th>Progress Status</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $i = 1 @endphp
                            @foreach($completedProjectList as $value)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $value->employee->name }}</td>
                                <td>{{ $value->title }}</td>
                                <td>{{ date('d-M-Y', strtotime($value->assign_date)) }}</td>
                                <td>
                                    <a class="btn btn-danger" href="{{ route('maintenance',$value->id) }}">Turn to Maintenance</a>
                                </td>
                                <td>{{ Str::limit($value->description,20) }}</td>
                                <td>
                                    <div class="action-buttons">
                                        <a class="btn btn-dark" href="{{ route('task.edit',$value->id) }}"><i class="fas fa-edit"></i></a>

                                        <form action="{{ route('task.destroy',$value->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                        </form>
                                    </div>

                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<!--/ Hoverable Table rows -->

@endsection
@push('js')
<script src="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.js"></script>
<script>
    new DataTable('#example', {
        select: true
    });

</script>
@endpush

resources/views/backend/dashboard/dashboard.blade.php
@extends('backend.partials.app')
@push('css')
<style>
    .bacground {
        background: beige;

    }

</style>
@endpush
@section('content')
<div class="container-xxl flex-grow-1 container-p-y ">
    <div class="row">

        <div class="col-lg-12 col-md-12 col-sm-12 order-1">
            <div class="row">


                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(177, 1, 1)">
                            <a href="{{ route('customerList') }}">
                                <span style="color: white">Total Client</span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $customer }} Person</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(212, 88, 4)">
                            <a href="{{ route('receivableCurrent') }}">
                                <span style="color: white">Receivable In <strong>{{ $currentMonthName }}</strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $receivableCurrent }} Tk.</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(175, 138, 14)">
                            <a href="{{ route('currentIncomeList') }}">
                                <span style="color: white">Income In <strong>{{ $currentMonthName }}</strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $incomeCurrent }} Tk.</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(175, 138, 14)">
                            <a href="{{ route('currentIncomeList') }}">
                                <span style="color: white">Unpaid In <strong>{{ $currentMonthName }}</strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $unpaidAmountCurrent }} Tk.</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(86, 175, 13)">
                            <a href="{{ route('totalIncomeList') }}">
                                <span style="color: white">Total Income<strong></strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $incomeAll }} Tk.</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(86, 175, 13)">
                            <a href="">
                                <span style="color: white">Cash In Hand<strong></strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $cashInHand }} Tk.</h3>
                            </a>
                        </div>
                    </div>
                </div>
                {{-- <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(16, 116, 16)">
                            <a href="{{ route('customer.index') }}">
                                <span style="color: white">Total Unpaid</span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $dueTotal }} Tk.</h3>
                            </a>
                        </div>
                    </div>
                </div> --}}
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(13, 170, 97)">
                            <a href="{{ route('activeProjectList') }}">
                                <span style="color: white">Ongoing Project<strong></strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $task }}</h3>
                            </a>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(9, 173, 152)">
                            <a href="{{ route('completedProjectList') }}">
                                <span style="color: white">Completed Project</span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $completed }}</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(9, 140, 173)">
                            <a href="{{ route('inactiveProjectList') }}">
                                <span style="color: white">Hold Project<strong></strong></span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $taskInactive }}</h3>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(12, 9, 173)">
                            <a href="{{ route('employee.create') }}">
                                <span style="color: white">Total Employee</span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $totalEmployee }}</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body" style="background: rgb(126, 9, 173)">
                            <a href="{{ route('maintenanceList') }}">
                                <span style="color: white">Total Maintanence Project</span>
                                <h3 style="color: white" class="card-title text-nowrap mb-1">{{ $maintanenceCount }}</h3>
                            </a>
                        </div>
                    </div>
                </div>



                {{-- @foreach($coursePay as $value)
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <span></span>
                            <h3 class="card-title text-nowrap mb-1"></h3>
                        </div>
                    </div>
                </div>
            @endforeach --}}



                {{-- @foreach ($batch as $item)
                @dd($item);
                <div class="col-lg-3 col-md-3 col-6 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <span class="card-title text-nowrap mb-1">{{ $item->batch->batch_name }}</span>
                {{-- @foreach($totalHighStd as $value) --}}
                {{-- <span class="card-title text-nowrap mb-1"></span>
                            @endforeach
                        </div>
                    </div>
                </div>
                @endforeach --}}

            </div>
        </div>
        <!-- Total Revenue -->
    </div>

</div>
<!-- / Content -->
@endsection

resources/views/backend/dashboard/maintenanceList.blade.php
@extends('backend.partials.app')
@section('content')
@push('css')
<style>
    .add-btn {
        width: 60px;
        height: 60px;
        background: #ef5252;
        display: inline-block;
        text-align: center;
        line-height: 60px;
        border-radius: 50%;
        font-size: 30px;
        color: aliceblue;
        cursor: pointer;
    }

    .customer-card {
        display: flex;
        justify-content: space-between;
    }

    .customer-container {
        margin: 0 0 310px 0;
    }

</style>
<link href="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
@endpush
<!-- Hoverable Table rows -->
<div class="container customer-container">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="customer-card mb-3" style="margin-top:-10px;">
                        <div class="area-h3">
                            <h2>Maintenance List</h2>
                        </div>
                        <div class="add-btn m-3">
                            <a href="{{ route('customer.create') }}" class="add-btn"><i class="fas fa-plus"></i></a>

                            <!-- Modal -->

                        </div>
                        {{-- <div class="print">
                            <a href="" class="btn btn-primary pdf">CSV</a>
                            <a href="" class="btn btn-primary pdf">Excel</a>
                             <a class="btn btn-primary pdf" href="">PDF</a>
                             <a class="btn btn-primary pdf btnprn" href="" onclick="print()">Print</a>
                            </div> --}}

                    </div>
                    <table class="table table-hover table-borderd" id="example">
                        <thead>
                            <tr>
                                <th>Serial No.</th>
                                <th>Name of Bussiness or Person</th>
                                <th>Name</th>
                                <th>Phone</th>
                               
                                {{-- <th>Actions</th> --}}
                            </tr>
                        </thead>
                        <tbody> @foreach($maintenance as $value)
                            <tr>
                                <td>{{$value->serial_number}}</td>
                                <td>{{$value->name_or_business}}</td>
                                <td>{{$value->name}}</td>
                                <td>{{$value->phone}}</td>
                                {{-- <td>
                                    <form action="{{ route('customer.destroy', $value->customers->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                </form>
                                </td> --}}
                            </tr> @endforeach </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<!--/ Hoverable Table rows -->

@endsection
@push('js')
<script src="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.js"></script>
<script>
    new DataTable('#example', {
        select: true
    });

</script>
@endpush