routes/web.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\BatchController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DefaultController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\CoursePayController;
use App\Http\Controllers\OurTeamController;
use App\Http\Controllers\RealEventController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\AdvocateController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\CashInHandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CreateAdminController;
use App\Http\Controllers\CustomerApproveController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerInvoiceController;
use App\Http\Controllers\CustomerTransactionController;
use App\Http\Controllers\DomainController;
use App\Http\Controllers\DomainHostingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EstimateController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\HostingController;
use App\Http\Controllers\InvestorController;
use App\Http\Controllers\InvestorPayController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\PermissionAssignController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SubModuleController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskUpdateController;
use App\Http\Controllers\TransactionController;
use App\Models\Transaction;
use Illuminate\Support\Facades\Route;


Route::redirect('/', 'dashboard');
Route::match(['get', 'post'], '/register', [AdminAuthController::class, 'register'])->name('register');
Route::match(['get', 'post'], '/login', [AdminAuthController::class, 'login'])->name('login');
Route::match('get', '/logout', [AdminAuthController::class, 'logout'])->name('admin.logout');
Route::match(['get', 'post'], '/my-profile/{id}', [AdminAuthController::class, 'myProfile'])->name('my.profile');
Route::match(['get', 'post'], '/change/password/{id}', [AdminAuthController::class, 'changePassword'])->name('change.password');

Route::group(['middleware' => ['adminAuth']], function () {
    Route::match(['get'], '/dashboard', [DashboardController::class, 'dashboard'])->name('admin.dashboard');

    //customer
    Route::resource('customer', CustomerController::class);
    //Product & Service
    Route::resource('service', ServiceController::class);
    //Traction
    Route::resource('transaction', TransactionController::class);
    //Invoice
    Route::resource('invoice', InvoiceController::class);
    //employee
    Route::resource('employee', EmployeeController::class);
    //task
    Route::resource('task', TaskController::class);
    //taskUpdate
    Route::resource('taskUdate', TaskUpdateController::class);

    //transaction_customer
    Route::post('/createdCustomer', [CustomerTransactionController::class, 'index'])->name('customer.transaction');
    Route::post('/invoiceCustomer', [CustomerInvoiceController::class, 'invoiceCustomer'])->name('customer.invoice');
    //attendance
    Route::get('/attendance',[AttendanceController::class,'Attendance'])->name('attendance');
    Route::post('/create/attendance',[AttendanceController::class,'createAttendance'])->name('create.attendance');
    Route::get('/get/attendance',[AttendanceController::class,'getAttendance'])->name('get.attendance');
    Route::get('/end/attendance/{id}',[AttendanceController::class,'endAttendance'])->name('end.attendance');
    Route::post('/update/attendance/{id}',[AttendanceController::class,'updateAttendance'])->name('update.attendance');
    Route::get('/unblockEmployee',[AttendanceController::class,'unblockEmployee'])->name('unblockEmployee');
    Route::post('/unblockEmployee',[AttendanceController::class,'unblockEmployeePost'])->name('unblockEmployeePost');
    Route::get('/delete/unblock{id}',[AttendanceController::class,'deleteUnblock'])->name('delete.unblock');
    //invoicePdf
    Route::get('/invoicePdf/{id}', [PdfController::class, 'invoicePdf'])->name('invoicePdf');

    //employeePrint
    Route::get('/employeePrint/{id}', [PdfController::class, 'employeePrint'])->name('employeePrint');

    //Task_status
    Route::get('taskStatus/{id}', [TaskController::class, 'taskStatus'])->name('taskStatus');
    //Task_progress_status
    Route::get('taskProgressStatus/{id}', [TaskController::class, 'taskProgressStatus'])->name('taskProgressStatus');
    //maintenanece
    Route::get('maintenance/{id}', [TaskController::class, 'maintenance'])->name('maintenance');
    Route::get('ongoing/{id}', [CustomerController::class, 'ongoing'])->name('ongoing');

    //ajax
    Route::post('/getPrice', [AjaxController::class, 'getPrice']);

    //customerList for dashboard
    Route::get('/customerList', [CustomerController::class, 'customerList'])->name('customerList');
    Route::post('/customerDelete/{id}', [CustomerController::class, 'customerDelete'])->name('customerDelete');
    //customer Approve
    Route::get('/customerApprove', [CustomerApproveController::class, 'customerApprove'])->name('customer.approve');
    
    //receivable Amount for dashboard
    Route::get('/receivableCurrent', [DashboardController::class, 'receivableCurrent'])->name('receivableCurrent');
    //CurrentIncome for dashboard
    Route::get('/currentIncomeList', [DashboardController::class, 'currentIncomeList'])->name('currentIncomeList');
    //totalIncome for dashboard
    Route::get('/totalIncomeList', [DashboardController::class, 'totalIncomeList'])->name('totalIncomeList');
    //activeProjectList for dashboard
    Route::get('/activeProjectList', [DashboardController::class, 'activeProjectList'])->name('activeProjectList');
    //inactiveProjectList for dashboard
    Route::get('/inactiveProjectList', [DashboardController::class, 'inactiveProjectList'])->name('inactiveProjectList');
    //completedProjectList for dashboard
    Route::get('/completedProjectList', [DashboardController::class, 'completedProjectList'])->name('completedProjectList');
    //maintenanceList
    Route::get('/maintenanceList', [DashboardController::class, 'maintenanceList'])->name('maintenanceList');
    // //investor_pay
    Route::match(['get', 'post'], '/investor_pay', [InvestorPayController::class, 'investor_pay'])->name('investor_pay');

    Route::match(['get'], '/payment/list', [InvestorPayController::class, 'paymentList'])->name('payment.list');

    Route::match(['get'], '/investorPay_delete/{id}', [InvestorPayController::class, 'investorPayDelete'])->name('investorPay_delete');
    //maintenance_get
    Route::match(['get', 'post'], '/maintenance_get', [MaintenanceController::class, 'maintenance_get'])->name('maintenance_get');
    //maintenance_list
    Route::match(['get'], '/maintenance_list', [MaintenanceController::class, 'maintenance_list'])->name('maintenance_list');
    Route::post('/mantenaceDelete/{id}',[MaintenanceController::class,'mantenaceDelete'])->name('mantenaceDelete');
    Route::match(['get','post'],'/maintenancePay',[MaintenanceController::class,'maintenancePay'])->name('maintenancePay');
    //maintenanceDue
    Route::match(['get'], '/maintenanceDue', [MaintenanceController::class, 'maintenanceDue'])->name('maintenanceDue');
    //maintenancePaid
    Route::match(['get'], '/maintenancePaid', [MaintenanceController::class, 'maintenancePaid'])->name('maintenancePaid');

    //estimate.create
    Route::match(['get','post'],'/estimate/create',[EstimateController::class,'estimate_create'])->name('estimate.create');
    Route::match(['get'],'/estimate/list',[EstimateController::class,'estimateList'])->name('estimateList');
    Route::match(['post'],'/estimateDestroy/{id}',[EstimateController::class,'estimateDestroy'])->name('estimateDestroy');
    Route::match(['get'],'/estimateView/{id}',[EstimateController::class,'estimateView'])->name('estimateView');
    Route::match(['get'],'/estimatePdf/{id}',[PdfController::class,'estimatePdf'])->name('estimatePdf');

    // //Task
    Route::match(['get'], '/getName', [AjaxController::class, 'getName'])->name('getName');
    Route::match(['get'], '/getMaintenanceAmount', [AjaxController::class, 'getMaintenanceAmount'])->name('getMaintenanceAmount');

    // //investorPay_print
    Route::match(['get'], '/investorPay_print/{id}', [PdfController::class, 'investorPay_print'])->name('investorPay_print');

    // //bookingInvoice
    Route::match(['get'], '/bookingInvoice/{id}', [PdfController::class, 'bookingInvoice'])->name('bookingInvoice');
    //investorPay_View
    Route::match(['get'],'/investorPay_View/{id}',[InvestorPayController::class,'investorPay_View'])->name('investorPay_View');
    //category.index
    Route::match(['get','post'],'/category/list',[CategoryController::class,'category_index'])->name('category.index');
    Route::match(['post'],'/category/delete/{id}',[CategoryController::class,'category_delete'])->name('category_delete');
    Route::match(['get'],'/expense/list',[ExpenseController::class,'expenselist'])->name('expenselist');
    Route::match(['get'],'/expensePost/list',[ExpenseController::class,'expensePost'])->name('expensePost');
    Route::match(['get','post'],'/expense/create',[ExpenseController::class,'expenseCreate'])->name('expenseCreate');
    

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Service;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //service
        $data = [];
        $data['active_menu'] = 'service';
        $data['page_title'] = 'List of Service';
        $service = Service::all();
        return view('backend.service.list_service', compact('data','service'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data = [];
        $data['active_menu'] = 'Customer';
        $data['page_title'] = 'Add Customer';
        return view('backend.service.add_service', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        Service::create([
            'name' => $request->name,
            'description' => $request->description,
            'price' => $request->price,
            'name' => $request->name,
        ]);
        return back()->with('message','Service Created Successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // $service = Service::find($id)
    }
}

resources/views/backend/service/add_service.blade.php
@extends('backend.partials.app')
@push('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-lg-12 mb-4 order-0">
            <div class="card">
                <div class="d-flex align-items-end row">
                    <div class="col-sm-12">
                        <div class="card-body">

                            <div class="row">
                                <!-- Basic Layout -->
                                <div class="col-xxl">
                                    <div class="card mb-2">
                                        <div class="card-body">
                                            @if (session('success'))
                                            <div class="alert slert-success timeout" style="color: green">{{ session('success') }}</div>
                                            @elseif (session('error'))
                                            <div class="alert slert-danger timeout">{{ session('error') }}</div>
                                            @endif
                                            <form action="{{ route('service.store') }}" method="post" enctype="multipart/form-data">
                                                @csrf
                                                <div class="row my-3">
                                                   <div style="text-align: center;">
                                                    <h2>New Product & Service</h2>
                                                   </div>


                                                    <div class="col-md-8 mx-auto ">
                                                        <label for="name" class="my-2">Name</label>
                                                        <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name">
                                                    </div>
                                                    <div class="col-md-8 mx-auto ">
                                                        <label for="description" class="my-2">Description</label>
                                                       <textarea class="form-control" name="description" id="description" cols="30" rows="10"></textarea>
                                                    </div>
                                                    {{-- <div class="col-md-8 mx-auto ">
                                                        <label for="price" class="my-2">Price</label>
                                                        <input type="text" name="price" id="price" class="form-control" placeholder="Enter Price">
                                                    </div> --}}



                                                </div>
                                                <div class="text-center">
                                                    <input type="submit" value="Submit" class="btn btn-primary">
                                                </div>
                                                <hr>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

</div>
@endsection

resources/views/backend/service/list_service.blade.php
@extends('backend.partials.app')
@section('content')
@push('css')
<style>

    .add-btn {
        width: 60px;
        height: 60px;
        background: #ef5252;
        display: inline-block;
        text-align: center;
        line-height: 60px;
        border-radius: 50%;
        font-size: 30px;
        color: aliceblue;
        cursor: pointer;
    }

    .customer-card {
        display: flex;
        justify-content: space-between;
    }

    .customer-container {
        margin: 0 0 310px 0;
    }

</style>
<link href="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
@endpush
<!-- Hoverable Table rows -->
<div class="container customer-container">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="customer-card mb-3" style="margin-top:-10px;">
                        <div class="area-h3">
                            <h2>Service List Table</h2>
                        </div>
                        <div class="add-btn m-3">
                            <a href="{{ route('service.create') }}" class="add-btn"><i class="fas fa-plus"></i></a>

                            <!-- Modal -->

                        </div>
                        {{-- <div class="print">
                            <a href="" class="btn btn-primary pdf">CSV</a>
                            <a href="" class="btn btn-primary pdf">Excel</a>
                             <a class="btn btn-primary pdf" href="">PDF</a>
                             <a class="btn btn-primary pdf btnprn" href="" onclick="print()">Print</a>
                            </div> --}}

                    </div>
                    <table class="table table-hover table-borderd" id="example">
                        <thead>
                            <tr>

                                <th>Name</th>

                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody> @foreach($service as $value)
                            <tr>

                                <td>{{$value->name}}</td>
                                <td>{{$value->description}}</td>
                                <td style="width: 121px;">
                                    <form style="display: inline-block;" action="{{ route('service.destroy', $value->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                    </form>

                                </td>
                            </tr> @endforeach </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<!--/ Hoverable Table rows -->

@endsection
@push('js')
<script src="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.js"></script>
<script>
    new DataTable('#example', {
        select: true
    });

</script>
@endpush